package com.suporte.tickets.entity;

public enum NotificacaoTipo {
    TICKET_ESCALONADO,
    ESCALONAMENTO_REMOVIDO,
    SLA_PRIMEIRO_ATENDIMENTO_VENCIDO,
    SLA_RESOLUCAO_VENCIDA,
    SLA_PRIMEIRO_ATENDIMENTO_PROXIMO,
    SLA_RESOLUCAO_PROXIMA
}
